-- MySQL Workbench Forward Engineering
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
-- ------------------------------------------------------- Schema swipe-- -----------------------------------------------------
-- ------------------------------------------------------- Schema swipe-- -----------------------------------------------------CREATE SCHEMA IF NOT EXISTS `swipe` DEFAULT CHARACTER SET utf8 ;USE `swipe` ;
-- ------------------------------------------------------- Table `swipe`.`location`-- -----------------------------------------------------DROP TABLE IF EXISTS `swipe`.`location` ;
CREATE TABLE IF NOT EXISTS `swipe`.`location` (  `idlocation` INT NOT NULL AUTO_INCREMENT,  `office_name` VARCHAR(45) NULL,  `office_address` VARCHAR(45) NULL,  `office_country` VARCHAR(45) NULL,  PRIMARY KEY (`idlocation`))ENGINE = InnoDB;
-- ------------------------------------------------------- Table `swipe`.`card`-- -----------------------------------------------------DROP TABLE IF EXISTS `swipe`.`card` ;
CREATE TABLE IF NOT EXISTS `swipe`.`card` (  `idcard` INT NOT NULL AUTO_INCREMENT,  `card_code` VARCHAR(45) NULL,  `card_name` VARCHAR(45) NULL,  `created` DATETIME NULL,  `active` TINYINT(1) NULL,  `issue_location` INT NOT NULL,  PRIMARY KEY (`idcard`, `issue_location`),  INDEX `fk_card_location1_idx` (`issue_location` ASC),  CONSTRAINT `fk_card_location1`    FOREIGN KEY (`issue_location`)    REFERENCES `swipe`.`location` (`idlocation`)    ON DELETE NO ACTION    ON UPDATE NO ACTION)ENGINE = InnoDB;
-- ------------------------------------------------------- Table `swipe`.`employee`-- -----------------------------------------------------DROP TABLE IF EXISTS `swipe`.`employee` ;
CREATE TABLE IF NOT EXISTS `swipe`.`employee` (  `idemployee` INT NOT NULL AUTO_INCREMENT,  `employee_name` VARCHAR(45) NULL,  `employee_type` VARCHAR(45) NULL,  `employee_email` VARCHAR(45) NULL,  `idlocation_parrent` INT NOT NULL,  PRIMARY KEY (`idemployee`, `idlocation_parrent`),  INDEX `fk_employee_location1_idx` (`idlocation_parrent` ASC),  CONSTRAINT `fk_employee_location1`    FOREIGN KEY (`idlocation_parrent`)    REFERENCES `swipe`.`location` (`idlocation`)    ON DELETE NO ACTION    ON UPDATE NO ACTION)ENGINE = InnoDB;
-- ------------------------------------------------------- Table `swipe`.`employee_card`-- -----------------------------------------------------DROP TABLE IF EXISTS `swipe`.`employee_card` ;
CREATE TABLE IF NOT EXISTS `swipe`.`employee_card` (  `idemployee_card` INT NOT NULL AUTO_INCREMENT,  `iidemployee` INT NOT NULL,  `idcard` INT NOT NULL,  PRIMARY KEY (`idemployee_card`, `idcard`, `iidemployee`),  INDEX `fk_employee_card_employee1_idx` (`iidemployee` ASC),  INDEX `fk_employee_card_card1_idx` (`idcard` ASC),  CONSTRAINT `fk_employee_card_employee1`    FOREIGN KEY (`iidemployee`)    REFERENCES `swipe`.`employee` (`idemployee`)    ON DELETE NO ACTION    ON UPDATE NO ACTION,  CONSTRAINT `fk_employee_card_card1`    FOREIGN KEY (`idcard`)    REFERENCES `swipe`.`card` (`idcard`)    ON DELETE NO ACTION    ON UPDATE NO ACTION)ENGINE = InnoDB;
-- ------------------------------------------------------- Table `swipe`.`pannel`-- -----------------------------------------------------DROP TABLE IF EXISTS `swipe`.`pannel` ;
CREATE TABLE IF NOT EXISTS `swipe`.`pannel` (  `idpannel` INT NOT NULL,  `pannel_name` VARCHAR(45) NULL,  `latitude` FLOAT(10,6) NULL,  `longitude` FLOAT(10,6) NULL,  `height` FLOAT(10,6) NULL,  `location_idlocation` INT NOT NULL,  PRIMARY KEY (`idpannel`, `location_idlocation`),  INDEX `fk_pannel_location1_idx` (`location_idlocation` ASC),  CONSTRAINT `fk_pannel_location1`    FOREIGN KEY (`location_idlocation`)    REFERENCES `swipe`.`location` (`idlocation`)    ON DELETE NO ACTION    ON UPDATE NO ACTION)ENGINE = InnoDB;
-- ------------------------------------------------------- Table `swipe`.`distance_rules`-- -----------------------------------------------------DROP TABLE IF EXISTS `swipe`.`distance_rules` ;
CREATE TABLE IF NOT EXISTS `swipe`.`distance_rules` (  `iddistance_rules` INT NOT NULL,  `distance_description` VARCHAR(45) NULL,  `idpannel_from` INT NOT NULL,  `idpannel_to` INT NOT NULL,  `minimum_duration` INT NULL,  PRIMARY KEY (`iddistance_rules`, `idpannel_from`, `idpannel_to`),  INDEX `fk_distance_rules_pannel1_idx` (`idpannel_from` ASC),  INDEX `fk_distance_rules_pannel2_idx` (`idpannel_to` ASC),  CONSTRAINT `fk_distance_rules_pannel1`    FOREIGN KEY (`idpannel_from`)    REFERENCES `swipe`.`pannel` (`idpannel`)    ON DELETE NO ACTION    ON UPDATE NO ACTION,  CONSTRAINT `fk_distance_rules_pannel2`    FOREIGN KEY (`idpannel_to`)    REFERENCES `swipe`.`pannel` (`idpannel`)    ON DELETE NO ACTION    ON UPDATE NO ACTION)ENGINE = InnoDB;
-- ------------------------------------------------------- Table `swipe`.`alert`-- -----------------------------------------------------DROP TABLE IF EXISTS `swipe`.`alert` ;
CREATE TABLE IF NOT EXISTS `swipe`.`alert` (  `idalert` INT NOT NULL,  `captured` DATETIME NULL,  `alert_type` VARCHAR(45) NULL,  `alert_description` VARCHAR(45) NULL,  `iddistance_rules` INT NOT NULL,  PRIMARY KEY (`idalert`),  INDEX `fk_alert_distance_rules1_idx` (`iddistance_rules` ASC),  CONSTRAINT `fk_alert_distance_rules1`    FOREIGN KEY (`iddistance_rules`)    REFERENCES `swipe`.`distance_rules` (`iddistance_rules`)    ON DELETE NO ACTION    ON UPDATE NO ACTION)ENGINE = InnoDB;
-- ------------------------------------------------------- Table `swipe`.`swipe`-- -----------------------------------------------------DROP TABLE IF EXISTS `swipe`.`swipe` ;
CREATE TABLE IF NOT EXISTS `swipe`.`swipe` (  `idswipe` INT NOT NULL AUTO_INCREMENT,  `idpannel` INT NOT NULL,  `idcard` INT NOT NULL,  `swipe_time` DATETIME NULL,  `validation_status` VARCHAR(45) NULL,  `alert_idalert` INT NOT NULL,  PRIMARY KEY (`idswipe`, `idpannel`, `idcard`),  INDEX `fk_swipe_alert1_idx` (`alert_idalert` ASC),  INDEX `fk_swipe_card1_idx` (`idcard` ASC),  INDEX `fk_swipe_pannel1_idx` (`idpannel` ASC),  CONSTRAINT `fk_swipe_alert1`    FOREIGN KEY (`alert_idalert`)    REFERENCES `swipe`.`alert` (`idalert`)    ON DELETE NO ACTION    ON UPDATE NO ACTION,  CONSTRAINT `fk_swipe_card1`    FOREIGN KEY (`idcard`)    REFERENCES `swipe`.`card` (`idcard`)    ON DELETE NO ACTION    ON UPDATE NO ACTION,  CONSTRAINT `fk_swipe_pannel1`    FOREIGN KEY (`idpannel`)    REFERENCES `swipe`.`pannel` (`idpannel`)    ON DELETE NO ACTION    ON UPDATE NO ACTION)ENGINE = InnoDB;
SET SQL_MODE=@OLD_SQL_MODE;SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
